Python/PythonDjango/email_validation/apps/email_checker/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', index, name="home"),
    url(r'^process$', views.process, name='process'),
    url(r'^success$', views.success, name='success'),
    url(r'^go_back$', views.go_back, name='go_back')
]

Python/PythonDjango/email_validation/email_validation/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.email_checker.urls', namespace='email_checker'))
]

Python/PythonDjango/email_validation/apps/email_checker/models.py
from __future__ import unicode_literals

from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=256)
    confirm_password = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

Python/PythonDjango/email_validation/apps/email_checker/views.py
from django.shortcuts import render, redirect
import re
from django.contrib import messages
from .models import Emails


# Create your views here.
def index(request):
    return render(request, "email_checker/index.html")

def process(request):
    # user_id = request.session
    if request.method == 'POST':
        server_email = request.POST['html_email']
        if len(server_email) < 1:
            messages.error(request, "NO EMAIL GIVEN")
            return redirect('email_checker:home')        
        if re.match('^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$', server_email):
            Emails.objects.create(email = server_email)
            return redirect('email_checker:success')
        else: 
            messages.error(request, "NOT AN EMAIL ADDRESS")
            return redirect('email_checker:home')

def success(request):
    last_email = Emails.objects.all().last
    context = {
        'last_email': last_email,
        'all_emails': Emails.objects.all()
    }
    return render(request, 'email_checker/success.html', context)

def go_back(request):
    return redirect('email_checker:home')

Python/PythonDjango/email_validation/apps/email_checker/templates/email_checker/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Email Validator</title>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssnormalize/cssnormalize-min.css">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'email_checker/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
</head>

{% load  %}
<body>
    {% if messages %}
        {% for message in messages %}
            <h2>{{ message }}</h2>
        {% endfor %}
    {% endif %}
    <img src="{% static 'email_checker/images/wrastle.gif' %}" alt="energy">
    <form action="{% url 'email_checker:process' %}" method="post">
        {% csrf_token %}
        <label for="html_email"><h1>enter a VALID email address:</h1></label>
        <input type="text" name="html_email"><br>
        <input type="submit" value="submit"><br>
    </form>
</body>

</html>

Python/PythonDjango/email_validation/apps/email_checker/templates/email_checker/success.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Success</title>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssnormalize/cssnormalize-min.css">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'email_checker/css/styles.css' %}" media="screen" title="no title"  charset="utf-8">
</head>

<body>
    <h1>Thank you for logging in {{last_email.email}}</h1>
    <form action="{% url 'email_checker:go_back' %}">
        <input type="submit" value="back" name="go_back">
    </form>
    <table>
        <tr>
            <th>email address</th>
            <th>created at</th>
        </tr>
    {% for email in all_emails %}
        <tr>
            <td>{{email.email}}</td>
            <td>{{email.created_at}}</td>
        </tr>
    {% endfor %}
    </table>

</body>

</html>